{% set name = "korean_lunar_calendar" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb2c485124a061016926bdea6d89efdf9b9fdbf16db55895b6cf1e5bec17b857

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - korean_lunar_calendar
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/usingsky/korean_lunar_calendar_py
  summary: Korean Lunar Calendar
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/usingsky/korean_lunar_calendar_py

extra:
  recipe-maintainers:
    - synapticarbors
